language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: pG42lAvKPNLFtDRvKunrLDOJfvnIMUb26Md5RSfZVFXgJRbpl3Y6vPexPJq4rE1Cz1cCLXFu5DKerRjybfga9StaYzwtTtHzYUisfseD67zS0KUokZn8eICAGXs3bXlWbJIPz3fH+rJf+aSSTiBLqnCiMI512zqCO6GD9WMOVBo=
